language: python
sudo: required
python:
    - "2.7"
env:
    - CKANVERSION=master
    - CKANVERSION=2.7
    - CKANVERSION=2.6
    - CKANVERSION=2.5
    - CKANVERSION=2.4
    - CKANVERSION=2.3
services:
    - postgresql
    - redis-server
install: bash bin/travis-build.bash
script: sh bin/travis-run.sh
after_success:
    - coveralls
